### ISSUE TITLE
%COMMANDER_PATH% does not expand in JVM_DLL

### ISSUE THREAD

**Issue by Konfekt** [moisescastellano/javadecompiler-tcplugin#3]
The path to the JVM_DLL cannot be found if it is given by the set environment variable`%COMMANDER_PATH%` instead of its value in the section `[JVM]` in the file `tc_javaplugin.ini`.

**Comment by Konfekt** [comment]
This is in contrast to the use of this environment variable in the other settings of `tc_javaplugin.ini`, where it works fine

**Comment by moisescastellano** [comment]
Hi Konfekt:
Thanks for reporting.
%COMMANDER_PATH% is set by TC to its own path, so do you mean you are trying to set the JVM dll path relative to the TC folder?
You are right, just now %COMMANDER_PATH% is being used to solve relative paths just for these 2 variables:
  - JAVA.TC.JAVALIB
  - JAVA.CLASS.PATH
and therefore JVM_DLL value is not using %COMMANDER_PATH%.
I take note of this idea in case is deemed useful, in the meanwhile you can put an absolute path in JVM_DLL.
Regards,
Moises

**Comment by Konfekt** [comment]
Dear @moisescastellano, exactly. It was just the idea of creating a portable version of Totalcommander including your plug-in and the JRE

**Comment by Konfekt** [comment]
I am closing this issue as it could be argued that it is the duty of the user to set %COMMANDER_PATH% which happens during install. In this case Total Commander was a portable application and %COMMANDER_PATH% unset. 
Still, inside Total Commander this environment variable is set and perhaps this plugin could read it; thus this issue is rather a feature request, albeit rather specialized.

**Comment by moisescastellano** [comment]
Fine. Thanks for the suggestion.
